name: academiview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.8
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  dio: ^5.4.0
  crypto: ^3.0.3
  flutter_pdfview: ^1.4.0+1
  path_provider: ^2.1.5
  webview_flutter: ^4.13.0  # Keep for mobile WebView support
  cupertino_icons: ^1.0.6
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  share_plus: ^11.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets directory if you have any
  # assets:
  #   - images/
  #   - icons/